---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: vagrant
    box: ubuntu/xenial64
provisioner:
  name: ansible
  inventory:
    host_vars:
      vagrant:
        ansible_connection: local
        ansible_user: vagrant
  playbooks:
    create: create.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
