---

- name: check if nginx already installed
  stat:
    path: /usr/sbin/nginx
  register: nginx_file_details

- name: update apt cache
  become: true
  apt:
    update_cache: yes
  when: not nginx_file_details.stat.exists

- name: install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: not nginx_file_details.stat.exists

- name: copy nginx.conf template
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/nginx/templates/nginx.conf.ctmpl.j2"
    dest: /etc/nginx/nginx.conf.ctmpl
  tags:
    - launch

- name: Render nginx Systemd Config
  template:
    src: "/{{ destination }}/provisioners/roles/nginx/templates/nginx.systemd.j2"
    dest: /etc/systemd/system/nginx.service
    mode: 0644
  notify: restart nginx
