---

- name: check if nginx already installed
  stat:
    path: /usr/sbin/nginx
  register: nginx_file_details

- name: update apt cache
  become: true
  apt:
    update_cache: yes
  when: not nginx_file_details.stat.exists

- name: install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: not nginx_file_details.stat.exists

- name: Start Nginx
  service:
    name: nginx
    state: started
  when: start
  tags:
    - launch

- name: delete existing nginx.conf file
  become: true
  file:
    dest: /etc/nginx/nginx.conf
    state: absent

# - name: copy nginx.conf consul template
#   become: true
#   copy:
#     src: /terraform/roles/nginx/files/nginx.conf.ctmpl
#       # /vagrant/provisioners/roles/nginx/files/nginx.conf.ctmpl
#     dest: /etc/nginx/nginx.conf.ctmpl
#     # owner: vagrant
#     # group: vagrant
#     remote_src: yes

- name: copy nginx.conf template
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/nginx/templates/nginx.conf.ctmpl.j2"
    dest: /etc/nginx/nginx.conf.ctmpl
  tags:
    - launch
