---

- name: Add VirtualBox repo keys
  apt_key:
    url: "https://www.virtualbox.org/download/{{ item }}.asc"
    state: present
  with_items:
    - oracle_vbox
    - oracle_vbox_2016

- name: Add VirtualBox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present
    update_cache: yes

- name: Install Virtualbox
  apt:
    name: virtualbox-{{ vb_version }}
    state: present
