---

- name: Add repository for PHP .
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install Wordpress requisites
  apt:
    name: "{{ item }}"
    # update_cache: yes
    state: present
  with_items:
    - php7.3
    - php7.3-mysql
    - php7.3-common
    - php7.3-tidy
    - php7.3-xml
    - php7.3-xmlrpc
    - php7.3-mbstring
    - php7.3-memcached
    - php7.3-soap
    - php7.3-curl
    - php7.3-zip
    - php7.3-gd
    - php7.3-bcmath
    - php7.3-imagick
    - php7.3-intl
    - mysql-client-core-5.7
    # - mysql-server
    # - python3-pymysql


- name: Install Wordpress Apache requisites
  apt:
    pkg:
      - apache2
    update_cache: yes
    state: present

- name: Create Wordpress home
  file:
    path: "{{ apache_dir }}"
    state: directory

- name: Download Wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: "/tmp/{{ wordpress_file }}"
  when: not import_www | bool

- name: Unarchive Wordpress
  become: true
  unarchive:
    src: "/tmp/{{ wordpress_file }}"
    dest: "{{ www_dir }}"
  when: not import_www | bool

- name: Delete Wordpress file
  become: true
  file:
    dest: "/tmp/{{ wordpress_file }}"
    state: absent
  when: not import_www | bool

- name: Wordpress Server config directory - apache2.conf
  shell: 'sudo sed -i -e "s/^<Directory \\/var\\/www.*$/<Directory \\/var\\/www\\/wordpress\\/>/" /etc/apache2/apache2.conf'

- name: Wordpress Server config directory - 000-default.conf
  shell: "sudo sed -i -e 's/DocumentRoot.*$/DocumentRoot \\/var\\/www\\/wordpress/' {{ item }}"
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-available/000-default.conf

- name: Setup Wordpress Server port - ports.conf
  shell: "sudo sed -i -e 's/^Listen.*$/Listen {{ apache_port }}/' /etc/apache2/ports.conf"
  when: change_port | bool

- name: Setup Wordpress Server port - /sites-available/000-default.conf
  shell: "sudo sed -i -e 's/^<VirtualHost.*$/<VirtualHost *:{{ apache_port }}>/' {{ item }}"
  with_items:
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-enabled/000-default.conf
  when: change_port | bool

- name: Enable override for S3 bucket images - apache2.conf
  shell: 'sed -i -e "/^<Directory \\/var\\/www\\/wordpress\\/>.*/{n;n;s/None.*$/All/;}" /etc/apache2/apache2.conf'

- name: Render wp-config file
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/wordpress/templates/wp-config.php.j2"
    dest: "{{ www_dir }}/wp-config.php"

- name: get wordpress file from S3 bucket
  aws_s3:
    bucket: "{{ s3_bucket_backup }}"
    object: "/{{ www_prefix }}/{{ backup_file }}"
    dest: "/{{ dest_dir }}/{{ backup_file }}"
    mode: get
  become: true
  when: import_www | bool

- name: unarchive wordpress files to /var/www/wordpress
  unarchive:
    src: "/{{ dest_dir }}/{{ backup_file }}"
    dest: "{{ apache_dir }}"
  when: import_www | bool

- name: Ensure directories are 0755
  command: find {{ www_dir }} -type d -exec chmod -c 0755 {} \;

- name: Ensure files are 0644
  command: find {{ www_dir }} -type f -exec chmod -c 0644 {} \;

- name: Render htaccess file for rewrites
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/wordpress/templates/.htaccess.j2"
    dest: "{{ apache_dir }}/.htaccess"
  notify: restart apache2

# check if ownership is apache
- name: Ownership of Wordpress content files
  file:
    path: "{{ www_dir }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  notify: restart apache2

- name: Enable the Rewrite Module
  shell: "sudo a2enmod rewrite"
