---

- name: update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Wordpress PHP requisites
  apt:
    pkg:
      - php
      - php-mysql
      - php-common
      - php-tidy
      - php-xml
      - php-xmlrpc
      - php-mbstring
      - php-memcached
      - php-soap
      - php-curl
      - php-zip
      - php-gd
      - php-bcmath
      - php-imagick
      - php-intl
    update_cache: yes
    state: present

- name: Install Wordpress Apache requisites
  apt:
    pkg:
      - apache2
    update_cache: yes
    state: present

- name: Download Wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: "/tmp/{{ wordpress_file }}"
  when: import_www == 'false'

- name: Unarchive Wordpress
  become: true
  unarchive:
    src: "/tmp/{{ wordpress_file }}"
    dest: "{{ www_dir }}"
  when: import_www == 'false'

- name: Delete Wordpress file
  become: true
  file:
    dest: "/tmp/{{ wordpress_file }}"
    state: absent
  when: import_www == 'false'

- name: Wordpress Server config directory - apache2.conf
  shell: 'sudo sed -i -e "s/^<Directory \\/var\\/www.*$/<Directory \\/var\\/www\\/wordpress\\/>/" /etc/apache2/apache2.conf'

- name: Wordpress Server config directory - 000-default.conf
  shell: "sudo sed -i -e 's/DocumentRoot.*$/DocumentRoot \\/var\\/www\\/wordpress/' {{ item }}"
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-available/000-default.conf

- name: Setup Wordpress Server port 8888 - ports.conf
  shell: "sudo sed -i -e 's/^Listen.*$/Listen 8888/' /etc/apache2/ports.conf"

- name: Setup Wordpress Server port 8888 - /sites-available/000-default.conf
  shell: "sudo sed -i -e 's/^<VirtualHost.*$/<VirtualHost *:8888>/' {{ item }}"
  with_items:
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-enabled/000-default.conf

- name: Enable override for S3 bucket images - apache2.conf
  shell: 'sed -i -e "/^<Directory \\/var\\/www\\/wordpress\\/>.*/{n;n;s/None.*$/All/;}" /etc/apache2/apache2.conf'

- name: Render wp-config file
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/wordpress/templates/wp-config.php.j2"
    dest: "{{ www_dir }}/wp-config.php"

- name: get wordpress file from S3 bucket
  aws_s3:
    bucket: "{{ s3_bucket_backup }}"
    object: "/{{ www_prefix }}/{{ backup_file }}"
    dest: "/{{ dest_dir }}/{{ backup_file }}"
    mode: get
  become: true
  when: import_www == 'true'

- name: unarchive wordpress files to /var/www/wordpress
  unarchive:
    src: "/{{ dest_dir }}/{{ backup_file }}"
    dest: "{{ www_dir }}"
  when: import_www == 'true'

- name: Ensure directories are 0755
  command: find {{ www_dir }} -type d -exec chmod -c 0755 {} \;

- name: Ensure files are 0644
  command: find {{ www_dir }} -type f -exec chmod -c 0644 {} \;

# check if ownership is apache
- name: Ownership of Wordpress content files
  file:
    path: "{{ www_dir }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Render htaccess file for rewrites
  become: true
  template:
    src: "/{{ destination }}/provisioners/roles/wordpress/templates/.htaccess.j2"
    dest: "{{ apache_dir }}/.htaccess"

- name: Enable the Rewrite Module
  shell: "sudo a2enmod rewrite"

- name: Enable apache
  service:
   name: apache2
   state: started
   enabled: true
