---
#consul template

- name: check if consultemplate already installed
  stat:
    path: /usr/local/bin/consul-template
  register: consul_template_file_details

- name: update apt cache
  become: true
  apt:
    update_cache: yes
  when: not consul_template_file_details.stat.exists


- name: Install dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - unzip
  when: not consul_template_file_details.stat.exists

- name: download consul-template
  become: true
  get_url:
    url: "{{ consul_t_url }}"
    dest: /usr/local/bin
  when: not consul_template_file_details.stat.exists

- name: Unarchive consul-template
  become: true
  unarchive:
    src: "/usr/local/bin/{{ consul_t_package_name }}"
    dest: /usr/local/bin
    remote_src: yes
  when: not consul_template_file_details.stat.exists

- name: delete consul-template zip file
  become: true
  file:
    dest: "/usr/local/bin/{{ consul_t_package_name }}"
    state: absent
  when: not consul_template_file_details.stat.exists

- name: Move HCL file
  template:
    src: "/{{ destination }}/provisioners/roles/consultemplate/templates/nginx.consul-template.hcl.j2"
    dest: /etc/nginx.consul-template.hcl
    mode: 0644

- name: Render consultemplate Systemd Config
  template:
    src: "/{{ destination }}/provisioners/roles/consultemplate/templates/consultemplate.systemd.j2"
    dest: /etc/systemd/system/consul-template.service
    mode: 0644
  notify: restart consul-template
